# Generated by Django 4.0.4 on 2022-06-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predmet',
            name='izborni',
            field=models.CharField(choices=[('Da', 'da'), ('Ne', 'ne')], max_length=50),
        ),
        migrations.AlterField(
            model_name='uloge',
            name='uloga',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('PROFESOR', 'Profesor')], default='STUDENT', max_length=8),
        ),
    ]
